### ISSUE TITLE
Text and graph out of sync

### ISSUE THREAD

**Issue by Gijsjan** [HuygensING/tag-aid-poc#1] opened 2016-02-07 19:58 UTC
See "uerbis" in Wi3818.

**Comment by renevanderark** [comment] 2016-02-08 07:42
I see. Probably this could be fixed by incorporating the rank information. This was something Tara said could be easily done via the */readings API call, so we could get away with merging this into the readings.js(on) data.

**Comment by renevanderark** [comment] 2016-02-08 07:57
So the problem is indeed with the assumption that the order of ID's in the nodes is correct with the read order, but it is not. The nod with ID n266 in the SVG comes after nodes with IDs in the 400s. The only way to fix this is indeed by using the ranks of the words to order them in the text in stead of the IDs. Luckily I reverse engineered this info from the SVG and if these ranks are indeed complete we could fix this. I will try that.

**Closed as completed** 2016-02-08 08:12 UTC
